// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label7;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label8;
// SCREEN: ui_seting
void ui_seting_screen_init(void);
extern lv_obj_t *ui_seting;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label9;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label10;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label11;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label12;
// SCREEN: ui_light
void ui_light_screen_init(void);
extern lv_obj_t *ui_light;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label13;
// SCREEN: ui_timeAndTianqi
void ui_timeAndTianqi_screen_init(void);
extern lv_obj_t *ui_timeAndTianqi;
void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label14;
// SCREEN: ui_IR
void ui_IR_screen_init(void);
extern lv_obj_t *ui_IR;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1849664379);   // assets\天气-雨天.png
LV_IMG_DECLARE( ui_img_933897233);   // assets\天气-雷电天气.png
LV_IMG_DECLARE( ui_img_1809350367);   // assets\天气-晴天.png
LV_IMG_DECLARE( ui_img_614732645);   // assets\天气-多云.png

LV_FONT_DECLARE( ui_font_rh16);
LV_FONT_DECLARE( ui_font_rh32);
LV_FONT_DECLARE( ui_font_rh64);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
