// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Keyboard2;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Checkbox2;
extern lv_obj_t *ui_Checkbox1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_Calendar1;
extern lv_obj_t *ui_TabPage3;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_TabPage4;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_576777566);   // assets\数字5.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
