// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
int keybordshow_Flag = 0;
void keybordshow(lv_event_t * e)
{
	if(keybordshow_Flag == 0)
		{lv_obj_clear_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );keybordshow_Flag=1;}
	else
		{lv_obj_add_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );keybordshow_Flag=0;}
}
