// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_timeAndTianqi_screen_init(void)
{
ui_timeAndTianqi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_timeAndTianqi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button7 = lv_btn_create(ui_timeAndTianqi);
lv_obj_set_width( ui_Button7, 100);
lv_obj_set_height( ui_Button7, 50);
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"返回");

lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}
